### ISSUE TITLE
Missing Plugin Error

### ISSUE THREAD

**Issue by Shvet** [paymentez/paymentez-flutter#4]
I am trying to implement your payment gateway and trying to test it but it is giving me error as shown below:

```
[+98557 ms] E/flutter (11581): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: MissingPluginException(No implementation found for method resync on channel checkout_plugin)
[        ] E/flutter (11581): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:154:7)
[        ] E/flutter (11581): <asynchronous suspension>
[        ] E/flutter (11581): #1      CheckoutPlugin._resync (package:checkout_plugin/checkout_plugin.dart:73:20)
[        ] E/flutter (11581): <asynchronous suspension>
[        ] E/flutter (11581): 
[   +7 ms] E/flutter (11581): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: MissingPluginException(No implementation found for method resync on channel checkout_plugin)
[        ] E/flutter (11581): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:154:7)
[        ] E/flutter (11581): <asynchronous suspension>
[        ] E/flutter (11581): #1      CheckoutPlugin._resync (package:checkout_plugin/checkout_plugin.dart:73:20)
[        ] E/flutter (11581): <asynchronous suspension>
[        ] E/flutter (11581): 
```

**Comment by EdisonAltamirano** [comment]
Shvet didi you solve it?, i am having the same error

**Comment by Shvet** [comment]
@EdisonAltamirano  I dont remember much but you can reinstall app and it may work.
